blog/auth_app/views.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from sqlalchemy.exc import IntegrityError

from blog.forms.user import RegistrationForm, LoginForm
from blog.models import User
from blog.models.database import db

auth_app = Blueprint("auth_app", __name__)
login_manager = LoginManager()
login_manager.login_view = "auth_app.login"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("auth_app.login"))


__all__ = ["login_manager", "auth_app", ]


@auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index_app.index'))
    form = LoginForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one_or_none()
        if user is None:
            return render_template("auth/login.html", form=form, error="username doesn't exist")
        if not user.validate_password(form.password.data):
            return render_template("auth/login.html", form=form, error="invalid username or password")
        login_user(user)
        return redirect(url_for("index_app.index"))
    return render_template("auth/login.html", form=form)


@auth_app.route("/logout/", endpoint="logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("index_app.index"))


@auth_app.route("/secret/")
@login_required
def secret_view():
    return "Super secret data"


@auth_app.route("/register/", methods=["GET", "POST"], endpoint="register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index_app.index'))
    error = None
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff=False,
        )
        user.password = form.password.data
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create user!")
            error = "Could not create user!"
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            return redirect(url_for('auth_app.login'))
    return render_template("auth/register.html", form=form, error=error)

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Hello base!{% endblock %}</title>
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet"></head>
  <body>

  <div class="container-xl">
{% include 'navbar.html' %}


    {% block body %}
Hello base!
{% endblock %}

</div>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  </body>
</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% for (endpoint, label) in [('users_app.list', 'Пользователи'), ('articles_app.list', 'Статьи'), ('authors_app.list', 'Авторы')] %}
          <a href="{{ url_for(endpoint) }}" class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
          {{ label }}
          </a>
        {% endfor %}
      </div>
      <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{ url_for('auth_app.logout') }}">Logout</a>
          {% else %}
            <a href="{{ url_for('auth_app.login') }}" class="nav-link {% if request.endpoint == 'login' -%}active{%- endif %}">Login</a>
            <a class="nav-link" href="{{ url_for('auth_app.register') }}">Registration</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>